source 'https://rubygems.org'

gem 'rake'
gem 'itamae'
gem 'serverspec'
gem 'itamae-plugin-recipe-rbenv'
gem 'itamae-plugin-recipe-plenv', github: 'katsyoshi/itamae-plugin-recipe-plenv'
gem 'itamae-plugin-recipe-pyenv', github: 'katsyoshi/itamae-plugin-recipe-pyenv'
gem 'itamae-plugin-recipe-langenv', github: 'katsyoshi/itamae-plugin-recipe-langenv'
gem 'ohai'
